version: 2
updates:
  # Keep npm/yarn dependencies updated
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keep GitHub Actions workflows updated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
